services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /home/kunal/Desktop/nextcloud:/var/www/html/
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data