# Gatus is not a part of the monitoring compose because it has to access the monitoring sites using the public URLs
# So it can monitor their accessaibility also.

version: "1"

services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports:
      - "7070:8080"
    volumes:
      - ./config.yaml:/config/config.yaml
      - ./data:/data
    environment:
      # Enable config watching (auto-reload)
      - GATUS_CONFIG_WATCHER=true

      ## For displaying DEBUG logs
      # - GATUS_LOG_LEVEL=DEBUG
