## fastchat deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastchat
  namespace: apps
  labels:
    source: self-project
    app: fastchat
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fastchat
  template:
    metadata:
      labels:
        app: fastchat
    spec:
      containers:
        - name: fastchat
          image: docker.io/kunalvirwal/portfolio:v11
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: SECRET_KEY
              value: "{{ .encryptedSecrets.SECRET_KEY }}"
            - name: MONGODB_URI
              value: "{{ .encryptedSecrets.MONGODB_URI }}"
