
# This docker compose is to setup an instance of nextcloud
# The folder nextcloud being mounted to /var/www/html must have owner and group www-data

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /home/kunal/Desktop/nextcloud:/var/www/html/
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data