
# This cluster role binding is between prom-ext-api-user in monitoring namespace and prometheus-external cluster role to grant read 
# access of cluster resources to the external prometheus. 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-external
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-external
subjects:
  - kind: ServiceAccount
    name: prom-ext-api-user
    namespace: monitoring
