
# This is a secret to access the prom-ext-api-user ServiceAccount in the monitoring namespace.

apiVersion: v1
kind: Secret
metadata:
  name: prom-ext-api-user-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: prom-ext-api-user
type: kubernetes.io/service-account-token
