
# This docker compose is to setup an instance of jenkins.

services:
  app:
    image: jenkins/jenkins
    restart: on-failure
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - /home/kunal/Desktop/jenkins:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    group_add:
      - "999" # Add user to docker group to access the docker socket