apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: fastchat
  eventWatcher:
    - matcher:
        name: fastchat-image-update
      handler:
        type: GIT_UPDATE
        config:
          replacements:
            - file: ../../apps/fastchat/deployment.yaml
              yamlField: $.spec.template.spec.containers[0].image
  input:
    manifests:
      - ../../apps/fastchat/deployment.yaml
      - ../../apps/fastchat/service.yaml
      - ../../apps/fastchat/ingress.yaml
    kubectlVersion: 1.32.5
  trigger:
    onOutOfSync:
      disabled: false
      minWindow: 0m
  encryption:
    encryptedSecrets: # These secrets are key encrypted and safe to push to github for running pipecd but still it is a better practice to keep the repo private
      SECRET_KEY: AgBZLYGYeSvTTiPNfast+Gk/t7VRIvIRoywPphDO5XfXFGvNRX4UELgBi4nvgcrb9zzi+AxMDIzGC5uSUruXqooydWcQMn9kvClrx6y7/aAOWPiVoJLdnuEnm5WlxVyfg+NlJu/zrOOP0ADO2xaN35aO1NS21JuojHCJ1wKj4SWvyRgP0EuQPQpypFZNrvsfqEt2HSD6Iq665a964hTZu7kEvLPDaU0KjrM5ry+7/NS0GJOsxBTZg+8fd95JfHotsCnwtV17y3t6t3I6E/1OZRDjOd8hL5WBsqw3xoz8xmdDb+xV1uU14RGuoAiMl6L2BuVHpX3ZPpgMXwMq0weDaqcT3S3BzcXNCqSaVF2/gktfDbxPCXxzAFw13GgiOXyayuFfNzsJGhT5adCSLBzDYxFvuj3fx8b+GHwxd+u1JpgSr8p+rOAmzJ5nCcV/nwUfv+MA8CKFnbIVsQxKWFTGe0GWegrpBkkQfYfQmub3q664XCjIuf82NeShCTDKP3E/gI2+DIyFuQYFTeYVMVbTXY/5RW7t+hCYkJoXBQ3VoE/sPKked7GMVrCanwYK+BlV3JkSThleBbdDePDn/AEX2rGwSOXNly0xwpfHpLSbmjecw50oHLS9FnXiQmOHVAB88HLfq7HoyOqw+vgbBIuD74zQDwla9nKxMaso5wBr4X3KSJrh7XCSYfgK3ulm+JpZvtTYKjzEQn++sLE=
      MONGODB_URI: AgBKqnrGaA4ddLTcXlHGx4Tz+UtvdN+YVzyoClx02cbzVTR5I5IU21mXFTooFqlEYdd6Ou/4yfEI/V87xd88BeKLE+M0qNkwP+0ZzqyCyuWpBBkSb6gCsq5tkqXIEGqq7yamYXyoiM7ScElroWcrHRZYVkkSHCx8KvNjzcl2+5SypiMOejxyb7YNUGqYKAU0rVxPI8E1KTC4hv4pRrVrHN8hY0j4P3kB7J6fxH9XYDHYNlvSUR8SIN0AKqlPjc1+FAnDTPwTt9t5HmG5NHSw7NNX0iPy5UL9fBZF1O7AUhCNXxkVR4Xf/29c6hSgjta+I0hQxWTBRnWrpWuS307FT43xdgv/EYSc8S3tEUj1C8/D6yKeKlUNJEDJF3Pr+wc/Cqz4aIoijqd2asdtdRNAZ90JIhsS1bIheI9+RsMSoyGnIpQh0Q0BX3MKhddnVKfmCdF8195RWKTvKHj8oyTQrIF9lZWuphOzJgpJQhzGR1Knr4wN4TmADwRV239RjwOeiJ35+hQ7R7znRfUhfRJLO5u7YpR+xJgC+YC5coIb4DqGw/REwkNDiQoEfEiK3bgdFfv+OS7kH0eTNJHpzcpLq7CVKEjdFen1c57YHSGMZrL1SY8jl8X22Qjli4ttqL8+AdzS3u8Ag7YjSopvujobkyhXHdID/+fKFnHkYWffp8VllDe+GmwZGjqJ5CYxNriIGslet2z6q+kbZx/aa7MWo7pnn97vXegvMs68ohxV0LMSKBjyveKG+aOVSQN3drrR5MwON5DuT0Usymq5MSTGLD7A9Cy66ndkGr9BmX5Dl0MxJ5oaXpWH9XrtjwkXp2HbyaRngA7q
    decryptionTargets:
      - ../../apps/fastchat/deployment.yaml

  description: |
    This app is a self made chat server that uses websockets under the hood.
