apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: portfolio
  input:
    manifests:
      - ../../apps/portfolio/secret.yaml
      - ../../apps/portfolio/deployment.yaml
      - ../../apps/portfolio/service.yaml
      - ../../apps/portfolio/ingress.yaml
    kubectlVersion: 1.32.5
  encryption:
    encryptedSecrets: # These secrets are key encrypted and safe to push to github for running pipecd but still it is a better practice to keep the repo private
      DOCKER_CONFIG_JSON: "AgAkVPd3hFsccmTpjaR6TIgilPpnpqzUt8JOlXu+Un+oWXIqMkTYUQYz0mBpwvuhdL9HVzodEtN28p2AODJMDBVvAaLyRe52741u5tkAaPJjbwL5/mxowVa0hC3oX4NmTEfV/EcIObAS6NKoPaEv8bhN9VP07V+YLxKrSvcXZ4A0mP7bNfOUoiIyTWn3dOFz7vy1RWtTfyUbUm57W9XROTPqvg4VxGeCf7Tl5b4vvgvyzxB2uUDSeavDlAJI5ExXwRZH3pzuGkpNw0EG0/Z1YKCLuEtqkL/68v8MITjj9SMOh+YBogcPGEVcHTGP7SK2rCTZSRmUMb95RSr1QIXZ1nU/b58VIzzQPVvmELW0p7Yg2A7n9j46kcBJ7knOfaeilJe1i2JFoBsyXuHddaOGkGRzQz7CDWB1KhfLsXEr2E37hzPiJKxFeTjtvEB/idvdB9sAMWK9pcsvje43RiPdlhTexp4V03SVJk4PvffY7zy300GMUNx0+jiTifgHdEgde6jH929j3Op71sh/ngHvlQ3DixarNql49KtKIW0Fz7JtYv8enxvpM51zG+D3h0E+VuUp5XJjnoAh/srsNebW/muoWL2APqPDE8QUz7xXZoeqcQql2fKM/UsmynjcUWT0cELo/zk/taQ/tCjT4kJo4gSblHvG0gNsyIy69qSZaHsyweX9l041JXbIrjS5Qc3gWkLkgU0dPeCdgmpwmAtmk//oYAMXPBtDl/8Tcjh19EGIbmQu23dd1BmeBSdrPeq4oekhzp2kySurw0zKFm97+kVgtmKuJ+ryKg2eH0xvp13U35I36BeSfjobypPbqWIqZS8EZEf9HC/BXUuc0GEWM/oWBMRH2OkG54+gSBERdddyciglkTfRAeWC32Aa35PgsAMAz4SfQbG+m+77qVI/ljuzC/3amALosuyksUjkLO55Lj+TglgWrXwGqoo4DltMciU99mLoARgvbc9reoW2AbmLxlCAAjkSvGKHy4pq3PIqWA2nKnEOo/8oGNGKPbkH3cOsE4fh82QXhYGScGZ3UQS/kRqcFtu1yB7iLopNaptAzJsrP21uJIum4/4tg3HVzIHKeqBRZuIK8KQjnSpTsRhi"
    decryptionTargets:
      - ../../apps/portfolio/secret.yaml
  description: |
    This is my self hosted portfolio.


