apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: portfolio
  eventWatcher:
    - matcher:
        name: portfolio-image-update
      handler:
        type: GIT_UPDATE
        config:
          replacements:
            - file: ../../apps/portfolio/deployment.yaml
              yamlField: $.spec.template.spec.containers[0].image
  input:
    manifests:
      - ../../apps/portfolio/secret.yaml
      - ../../apps/portfolio/deployment.yaml
      - ../../apps/portfolio/service.yaml
      - ../../apps/portfolio/ingress.yaml
    kubectlVersion: 1.32.5
  trigger:
    onOutOfSync:
      disabled: false
      minWindow: 0m
  encryption:
    encryptedSecrets: # These secrets are key encrypted and safe to push to github for running pipecd but still it is a better practice to keep the repo private
      DOCKER_CONFIG_JSON: "AgByrzMQ7oY8Ws9gHQWYx0rUJ5/sIYcS0pKswzcMFgBg+H6pXWhyCyzmhU2wnQA1l4WuH9DQ1QtwUHIyDEqjcPZ+uKkEuU3/bsVJ5WKnvW1/i7WIG0nqCN4PK/5gTfq1uGUQeWGJn8tF8nqVE0GWW6wBHJcThxfS1zmL6kZ90D8rTPOzJoVzTKUy38ExRD1orV03THg8FLRuQ4wWEk4w4TRt+tKeT3SC80GI4gtR1k0PDPqWghJvkeKaRFf9bbFu2W75XI/olLWQGjYusg1IIKEeht+/5LNBTPk0f/JenUMNc9gl9g9yInN6T0WOAfXg57MeFR4yUh8Hy/s0wnz/qpZ+/Q5u4q+mtpOfJVJ2PhEWyCJnRZrFNHHHFFolwFNvdZl6/3LqoWWzzIAeNnNnVp+ixD5H+Nr1vcq9ot19K7EtYV/inOh97prgfeY3k/obXY9MHDERFvftxTyh9Yw7niklyY83TmKmUrVXDCjNAg2PculvA0x34BkvPzmH81WPESY7B/+AWaSR+nZ7FKZ7nSReZLz2efVwi5hJWLYlcLN6/PdHSCukW2HLGsLRzjWbViRXdIE18hXMSGyrVV3/YFzFPwBuQbeF90f2K2tpgNtq9U9APCCdAjrSoGwezavAVyhzlsawyo3UJ26BUcpYU4GjxlIEx56cORH8TQwA51uTH1Rpv5SUF6YUz/Dgv43uR0cneD2tucHlKnvebOGrSVStGOQ7UueVB1uhmaZicvonDZb4kD/CiiOGVY65V1qXiKhCBPVJAldfM5s4sAB++3QhXdb9j1j+lRnDn0yDwa5f4HRNRQmgrUCNsiQee3cqCbhLIlj3rirL3j5Q1fXWnVCJ+fOZ8VIzrAkZKwYvH1kKh6bABHhdxCj5LX3vd8G7c7dCKX3WU+5IcjkPAlPGWwPTfHiESAODUaTDPSsvSK/rsHLe2xAAd3uxUehwSBSvB7bA/ciBAUBuwX2cSk7dLLqIHjBYpRDUK8KoUuzKnuyvod7bBGUv/g6VO/6Ad2BaMvKMSnwfyywUhbcAraOMbDz+a/x+Qx495g0DqS5+1Kypj3FBwWXoYP9+xSGnVZkXB1vWLi+3N5iYCy/N0sKdj2H9niAfNB489ouhCc2upGujAhq7uTk2WfOiH72gCg==" #"AgAkVPd3hFsccmTpjaR6TIgilPpnpqzUt8JOlXu+Un+oWXIqMkTYUQYz0mBpwvuhdL9HVzodEtN28p2AODJMDBVvAaLyRe52741u5tkAaPJjbwL5/mxowVa0hC3oX4NmTEfV/EcIObAS6NKoPaEv8bhN9VP07V+YLxKrSvcXZ4A0mP7bNfOUoiIyTWn3dOFz7vy1RWtTfyUbUm57W9XROTPqvg4VxGeCf7Tl5b4vvgvyzxB2uUDSeavDlAJI5ExXwRZH3pzuGkpNw0EG0/Z1YKCLuEtqkL/68v8MITjj9SMOh+YBogcPGEVcHTGP7SK2rCTZSRmUMb95RSr1QIXZ1nU/b58VIzzQPVvmELW0p7Yg2A7n9j46kcBJ7knOfaeilJe1i2JFoBsyXuHddaOGkGRzQz7CDWB1KhfLsXEr2E37hzPiJKxFeTjtvEB/idvdB9sAMWK9pcsvje43RiPdlhTexp4V03SVJk4PvffY7zy300GMUNx0+jiTifgHdEgde6jH929j3Op71sh/ngHvlQ3DixarNql49KtKIW0Fz7JtYv8enxvpM51zG+D3h0E+VuUp5XJjnoAh/srsNebW/muoWL2APqPDE8QUz7xXZoeqcQql2fKM/UsmynjcUWT0cELo/zk/taQ/tCjT4kJo4gSblHvG0gNsyIy69qSZaHsyweX9l041JXbIrjS5Qc3gWkLkgU0dPeCdgmpwmAtmk//oYAMXPBtDl/8Tcjh19EGIbmQu23dd1BmeBSdrPeq4oekhzp2kySurw0zKFm97+kVgtmKuJ+ryKg2eH0xvp13U35I36BeSfjobypPbqWIqZS8EZEf9HC/BXUuc0GEWM/oWBMRH2OkG54+gSBERdddyciglkTfRAeWC32Aa35PgsAMAz4SfQbG+m+77qVI/ljuzC/3amALosuyksUjkLO55Lj+TglgWrXwGqoo4DltMciU99mLoARgvbc9reoW2AbmLxlCAAjkSvGKHy4pq3PIqWA2nKnEOo/8oGNGKPbkH3cOsE4fh82QXhYGScGZ3UQS/kRqcFtu1yB7iLopNaptAzJsrP21uJIum4/4tg3HVzIHKeqBRZuIK8KQjnSpTsRhi"
    decryptionTargets:
      - ../../apps/portfolio/secret.yaml
  description: |
    This is my self hosted portfolio.


