# docker-registry secret

apiVersion: v1
kind: Secret
metadata:
  name: secret-dockerhub/portfolio
  namespace: apps
  labels:
    app: portfolio
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .encryptedSecrets.DOCKER_CONFIG_JSON }}"