##  homarr secret

apiVersion: v1
kind: Secret
metadata:
  name: secret-homarr
  namespace: apps
  labels:
    app: homarr
type: Opaque
data:
  SECRET_ENCRYPTION_KEY: "XXXX...YYYY" # use `echo $(openssl rand -hex 32) | base64 -w 0` to generate a base 64 encoded secret